{
 "title": "Spring Boot Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"product-service:8081\", job=\"product_service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"product-service:8081\", area=\"heap\"}) / sum(jvm_memory_max_bytes{instance=\"product-service:8081\", area=\"heap\"}) * 100",
     "legendFormat": "Heap Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"product-service:8081\"}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}